// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: protobuf/src/api.proto

package testv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on PublishTestMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PublishTestMessageRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Data

	return nil
}

// PublishTestMessageRequestValidationError is the validation error returned by
// PublishTestMessageRequest.Validate if the designated constraints aren't met.
type PublishTestMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PublishTestMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PublishTestMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PublishTestMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PublishTestMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PublishTestMessageRequestValidationError) ErrorName() string {
	return "PublishTestMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PublishTestMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPublishTestMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PublishTestMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PublishTestMessageRequestValidationError{}

// Validate checks the field values on PubSubRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PubSubRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PubSubRequestValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Subscription

	return nil
}

// PubSubRequestValidationError is the validation error returned by
// PubSubRequest.Validate if the designated constraints aren't met.
type PubSubRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PubSubRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PubSubRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PubSubRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PubSubRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PubSubRequestValidationError) ErrorName() string { return "PubSubRequestValidationError" }

// Error satisfies the builtin error interface
func (e PubSubRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPubSubRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PubSubRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PubSubRequestValidationError{}

// Validate checks the field values on TestMessage with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TestMessage) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Data

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestMessageValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// TestMessageValidationError is the validation error returned by
// TestMessage.Validate if the designated constraints aren't met.
type TestMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestMessageValidationError) ErrorName() string { return "TestMessageValidationError" }

// Error satisfies the builtin error interface
func (e TestMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestMessageValidationError{}
